DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS doctor_address CASCADE;
DROP TABLE IF EXISTS patient_address CASCADE;
